baseURL = "/"
languageCode = "zh-cn"
title = "维森视觉检测仪器网"
theme = "ananke"

# 启用分类功能
[taxonomies]
  category = "categories"
  tag = "tags"

# 分页设置
paginate = 12

# 菜单配置
[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "产品中心"
    url = "/products/"
    weight = 2
  [[menu.main]]
    name = "资讯中心"
    url = "/news/"
    weight = 3
  [[menu.main]]
    name = "关于我们"
    url = "/about/"
    weight = 4

# 主题参数
[params]
  # 网站描述
  description = "专业的视觉检测设备信息与资讯发布平台"
  
  # 社交媒体链接
  [params.social]
    github = "https://github.com/yourusername"
    twitter = "https://twitter.com/yourusername"
    linkedin = "https://linkedin.com/in/yourusername"
    
  # 首页设置
  [params.home]
    # 产品分类轮播
    product_category_title = "产品分类"
    product_category_subtitle = "专业的视觉检测设备分类"
    
    # 新品推荐
    new_product_title = "新品推荐"
    new_product_subtitle = "最新上架的视觉检测设备"
    
    # 应用领域
    application_areas_title = "应用领域"
    application_areas_subtitle = "视觉检测技术在各行业的应用"
    
    # 应用案例
    application_cases_title = "应用案例"
    application_cases_subtitle = "成功案例展示"
    
    # 资讯中心
    news_center_title = "资讯中心"
    news_center_subtitle = "了解最新行业动态与展会信息"
    
    # 合作伙伴
    partner_companies_title = "合作伙伴"
    partner_companies_subtitle = "值得信赖的合作伙伴" 