baseURL = 'https://visndt.com/'
languageCode = 'zh-cn'
title = '维森视觉检测仪器'
theme = 'ananke'

# 启用分类功能
[taxonomies]
  category = 'categories'
  tag = 'tags'

# 分页设置
paginate = 12

# 菜单配置
[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "产品中心"
    url = "/products"
    weight = 20
  [[menu.main]]
    name = "应用领域"
    url = "/applications"
    weight = 30
  [[menu.main]]
    name = "应用案例"
    url = "/cases"
    weight = 40
  [[menu.main]]
    name = "资讯中心"
    url = "/news"
    weight = 50
  [[menu.main]]
    name = "定制中心"
    url = "/customs"
    weight = 60
  [[menu.main]]
    name = "商务服务"
    url = "/cooperation"
    weight = 70

# 主题参数
[params]
  # 网站描述
  description = "专业的视觉检测设备信息与资讯发布平台"
  
  # 首页设置
  [params.home]
    # 产品分类
    product_category_title = "产品分类"
    product_category_subtitle = "专业的视觉检测设备分类"
    
    # 新品推荐
    new_product_title = "新品推荐"
    new_product_subtitle = "最新上架的视觉检测设备"
    
    # 应用领域
    application_areas_title = "应用领域"
    application_areas_subtitle = "视觉检测技术在各行业的应用"
    
    # 应用案例
    application_cases_title = "应用案例"
    application_cases_subtitle = "成功案例展示"
    
    # 资讯中心
    news_center_title = "资讯中心"
    news_center_subtitle = "了解最新行业动态与展会信息"
    
    # 合作伙伴
    partner_companies_title = "合作伙伴"
    partner_companies_subtitle = "值得信赖的合作伙伴"

  # 轮播图配置
  [[params.carousel_images]]
    title = "专业的工业内窥镜解决方案"
    description = "为工业检测提供高品质、高效率的内窥镜设备"
    link = "/products"
    alt = "工业内窥镜解决方案"
    image = "/images/carousel/carousel-1.jpg"

  [[params.carousel_images]]
    title = "全方位的应用领域支持"
    description = "覆盖航空航天、能源电力、机械制造等多个领域"
    link = "/applications"
    alt = "应用领域展示"
    image = "/images/carousel/carousel-2.jpg"

  [[params.carousel_images]]
    title = "创新的检测技术"
    description = "持续创新，为客户提供更好的检测体验"
    link = "/cases"
    alt = "检测技术展示"
    image = "/images/carousel/carousel-3.webp"

# 媒体类型配置
[mediaTypes]
[mediaTypes."application/json"]
  suffixes = ["json"]

# 搜索索引配置
[outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "search-index"
  isPlainText = true

# 输出配置
[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
