baseURL = 'https://visndt.com/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = '维森视觉检测仪器'
theme = 'ananke'

# 中文字符处理配置
hasCJKLanguage = true

# 启用分类功能
[taxonomies]
  category = 'categories'
  tag = 'tags'

# 分页设置
paginate = 12

# 菜单配置
[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "产品中心"
    url = "/products"
    weight = 20

  [[menu.main]]
    name = "资讯中心"
    url = "/news"
    weight = 50
  [[menu.main]]
    name = "定制中心"
    url = "/customs"
    weight = 60
  [[menu.main]]
    name = "商务服务"
    url = "/cooperation"
    weight = 70

# SEO配置
enableRobotsTXT = true
enableGitInfo = true

# 主题参数
[params]
  # 网站描述
  description = "专业的视觉检测设备信息与资讯发布平台，提供工业内窥镜、检测相机等产品信息，为制造业提供优质的检测解决方案"

  # SEO参数
  keywords = "工业内窥镜,视觉检测,检测设备,工业检测,内窥镜,检测仪器,维森,VisNDT"
  author = "维森·视觉检测仪器"

  # 社交媒体
  [params.social]
    # 可以添加社交媒体链接

  # 分析工具
  [params.analytics]
    # Google Analytics
    google = ""
    # 百度统计
    baidu = ""
  
  # 首页设置
  [params.home]
    # 产品分类
    product_category_title = "产品分类"
    product_category_subtitle = "专业的视觉检测设备分类"
    
    # 新品推荐
    new_product_title = "新品推荐"
    new_product_subtitle = "最新上架的视觉检测设备"
    
    # 应用领域
    application_areas_title = "应用领域"
    application_areas_subtitle = "视觉检测技术在各行业的应用"
    
    # 应用案例
    application_cases_title = "应用案例"
    application_cases_subtitle = "成功案例展示"
    
    # 资讯中心
    news_center_title = "资讯中心"
    news_center_subtitle = "了解最新行业动态与展会信息"
    
    # 合作伙伴
    partner_companies_title = "合作伙伴"
    partner_companies_subtitle = "值得信赖的合作伙伴"

  # 轮播图配置
  [[params.carousel_images]]
    title = "专业的工业内窥镜解决方案"
    description = "为工业检测提供高品质、高效率的内窥镜设备"
    link = "/products"
    alt = "工业内窥镜解决方案"
    image = "/images/banners/home/carousel_general_carousel-1_original_v1.jpg"

  [[params.carousel_images]]
    title = "全方位的应用领域支持"
    description = "覆盖航空航天、能源电力、机械制造等多个领域"
    link = "/applications"
    alt = "应用领域展示"
    image = "/images/banners/home/carousel_general_carousel-2_original_v1.jpg"

  [[params.carousel_images]]
    title = "创新的检测技术"
    description = "持续创新，为客户提供更好的检测体验"
    link = "/cases"
    alt = "检测技术展示"
    image = "/images/banners/home/carousel_general_carousel-3_original_v1.webp"

# 媒体类型配置
[mediaTypes]
[mediaTypes."application/json"]
  suffixes = ["json"]

# 搜索索引配置
[outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "search-index"
  isPlainText = true

# 产品索引配置
[outputFormats.ProductIndex]
  mediaType = "application/json"
  baseName = "products-index"
  isPlainText = true

# 输出配置
[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "ProductIndex"]

# Markup配置 - 优化中文处理
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = false
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
  [markup.highlight]
    style = 'github'
    lineNos = true
    codeFences = true
    guessSyntax = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
    ordered = false
