[build]
  publish = "public"
  command = "hugo --minify"

[build.environment]
  HUGO_VERSION = "0.147.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  # 编码环境变量
  LC_ALL = "zh_CN.UTF-8"
  LANG = "zh_CN.UTF-8"

[context.production.environment]
  HUGO_ENV = "production"
  LC_ALL = "zh_CN.UTF-8"
  LANG = "zh_CN.UTF-8"

[dev]
  port = 8888
  targetPort = 1313
  publish = "public"
  autoLaunch = true

# HTTP头部设置 - 确保正确的编码
[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"

# Netlify Identity and Git Gateway Configuration
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; img-src 'self' data: https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; font-src 'self' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; connect-src 'self' https://identity.netlify.com https://api.netlify.com"

# Identity and Git Gateway Redirects
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/git/github"
  to = "/admin/index.html"
  status = 200

# 处理动态路由
[[redirects]]
  from = "/products/*"
  to = "/products/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/news/*"
  to = "/news/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/applications/*"
  to = "/applications/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/cases/*"
  to = "/cases/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/customs/*"
  to = "/customs/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/cooperation/*"
  to = "/cooperation/:splat"
  status = 200
  force = false

# 处理其他路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 身份验证回调处理
[[redirects]]
  from = "/.netlify/identity/verify"
  to = "/identity-callback.html"
  status = 200

# 安全头部配置
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self' https://identity.netlify.com https://unpkg.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://identity.netlify.com https://unpkg.com; style-src 'self' 'unsafe-inline' https://unpkg.com; img-src 'self' data: https://unpkg.com; font-src 'self' data: https://unpkg.com; connect-src 'self' https://identity.netlify.com https://api.netlify.com"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"